apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aegis.engine.fullname" . }}
  labels:
    component: {{ .Values.engine.name }}
{{ include "aegis.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.engine.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aegis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: {{ .Values.engine.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aegis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: {{ .Values.engine.name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/usr/local/bin/aegis-engine']
          ports:
            - name: http
              containerPort: 3210
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Singapore
          volumeMounts:
            - name: config
              mountPath: aegis.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.engine.resources | nindent 12 }}
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          secret:
            defaultMode: 420
            items:
              - key: config.yaml
                path: config.yaml
            secretName: {{ .Values.existingSecret }}
