apiVersion: v1
kind: Service
metadata:
  {{- if .Values.engine.service.annotations }}
  annotations:
{{ toYaml .Values.engine.service.annotations | indent 4 }}
  {{- end }}
  name: {{ template "aegis.fullname" .}}-engine
  labels:
    app.kubernetes.io/name: {{ include "aegis.name" . }}
    helm.sh/chart: {{ include "aegis.chart" . }}
    component: engine
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if and (.Values.engine.service.nodePort) (eq .Values.engine.service.type "NodePort") }}
      nodePort: {{ .Values.engine.service.nodePort }}
{{- end }}
{{- if .Values.engine.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.engine.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "aegis.name" . }}
    component: engine
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.engine.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
